import type { ActivityCategory, ActivityDefinition, DataType, Frequency } from "@/domain/types";

/** Official JOMA library table provided by product owner. Not interim seed. */
const ROWS = [
  { code: "ACT001", name: "ورزش", category: "سلامت جسم" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "DURATION" as DataType, dailyTarget: 30, weeklyTarget: 150, monthlyTarget: 600, weight: 5, sticker: "🏃", color: "#E85D75" },
  { code: "ACT002", name: "نوشیدن آب", category: "سلامت جسم" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "NUMERIC" as DataType, dailyTarget: 6, weeklyTarget: 42, monthlyTarget: 180, weight: 4, sticker: "💧", color: "#4F9FC4" },
  { code: "ACT003", name: "پیاده‌روی", category: "سلامت جسم" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "DURATION" as DataType, dailyTarget: 20, weeklyTarget: 100, monthlyTarget: 400, weight: 4, sticker: "🚶", color: "#5AA469" },
  { code: "ACT004", name: "مصرف میوه", category: "سلامت جسم" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "NUMERIC" as DataType, dailyTarget: 2, weeklyTarget: 14, monthlyTarget: 60, weight: 3, sticker: "🍎", color: "#D95D5D" },
  { code: "ACT005", name: "خواب کافی", category: "خواب و استراحت" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "DURATION" as DataType, dailyTarget: 7, weeklyTarget: 49, monthlyTarget: 210, weight: 5, sticker: "🌙", color: "#5964B4" },
  { code: "ACT006", name: "ساعت خواب منظم", category: "خواب و استراحت" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "BOOLEAN" as DataType, dailyTarget: 1, weeklyTarget: 7, monthlyTarget: 30, weight: 4, sticker: "⏰", color: "#6D75B8" },
  { code: "ACT007", name: "مدیتیشن", category: "سلامت روان" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "DURATION" as DataType, dailyTarget: 10, weeklyTarget: 50, monthlyTarget: 200, weight: 4, sticker: "🧘", color: "#7C6CE7" },
  { code: "ACT008", name: "تمرین تنفس", category: "سلامت روان" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "DURATION" as DataType, dailyTarget: 5, weeklyTarget: 35, monthlyTarget: 150, weight: 4, sticker: "🌬️", color: "#769FCD" },
  { code: "ACT009", name: "ثبت حال روزانه", category: "سلامت روان" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "RATING" as DataType, dailyTarget: 1, weeklyTarget: 7, monthlyTarget: 30, weight: 5, sticker: "📓", color: "#E9A23B" },
  { code: "ACT010", name: "مطالعه بدون حواس‌پرتی", category: "تمرکز و ذهن" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "DURATION" as DataType, dailyTarget: 30, weeklyTarget: 150, monthlyTarget: 600, weight: 5, sticker: "🎯", color: "#4F7CAC" },
  { code: "ACT011", name: "زمان بدون موبایل", category: "تمرکز و ذهن" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "DURATION" as DataType, dailyTarget: 30, weeklyTarget: 150, monthlyTarget: 600, weight: 4, sticker: "📵", color: "#5B8E7D" },
  { code: "ACT012", name: "نوشتن برنامه روزانه", category: "تمرکز و ذهن" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "BOOLEAN" as DataType, dailyTarget: 1, weeklyTarget: 7, monthlyTarget: 30, weight: 4, sticker: "📝", color: "#7C8C6C" },
  { code: "ACT013", name: "مطالعه", category: "یادگیری" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "DURATION" as DataType, dailyTarget: 30, weeklyTarget: 150, monthlyTarget: 600, weight: 4, sticker: "📚", color: "#D99A2B" },
  { code: "ACT014", name: "یادگیری مهارت جدید", category: "رشد فردی" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "DURATION" as DataType, dailyTarget: 20, weeklyTarget: 100, monthlyTarget: 400, weight: 4, sticker: "🛠️", color: "#5AA469" },
  { code: "ACT015", name: "نوشتن اهداف", category: "رشد فردی" as ActivityCategory, frequency: "WEEKLY" as Frequency, dataType: "BOOLEAN" as DataType, dailyTarget: 1, weeklyTarget: 3, monthlyTarget: 4, weight: 4, sticker: "⭐", color: "#8C6BB1" },
  { code: "ACT016", name: "گفت‌وگوی باکیفیت با همسر", category: "روابط" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "DURATION" as DataType, dailyTarget: 15, weeklyTarget: 105, monthlyTarget: 450, weight: 5, sticker: "💑", color: "#D66BA0" },
  { code: "ACT017", name: "قدردانی از همسر", category: "روابط" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "BOOLEAN" as DataType, dailyTarget: 1, weeklyTarget: 7, monthlyTarget: 30, weight: 4, sticker: "🙏", color: "#C7D4A0" },
  { code: "ACT018", name: "قرار دونفره", category: "روابط" as ActivityCategory, frequency: "WEEKLY" as Frequency, dataType: "DURATION" as DataType, dailyTarget: 0, weeklyTarget: 2, monthlyTarget: 8, weight: 5, sticker: "☕", color: "#C06C84" },
  { code: "ACT019", name: "تماس با خانواده", category: "خانواده" as ActivityCategory, frequency: "WEEKLY" as Frequency, dataType: "DURATION" as DataType, dailyTarget: 0, weeklyTarget: 30, monthlyTarget: 120, weight: 3, sticker: "📞", color: "#C7D4A0" },
  { code: "ACT020", name: "دیدار با خانواده", category: "خانواده" as ActivityCategory, frequency: "WEEKLY" as Frequency, dataType: "DURATION" as DataType, dailyTarget: 0, weeklyTarget: 2, monthlyTarget: 8, weight: 4, sticker: "🏠", color: "#B97855" },
  { code: "ACT021", name: "نوشتن سه نکته مثبت", category: "ذهن‌آگاهی" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "NUMERIC" as DataType, dailyTarget: 3, weeklyTarget: 21, monthlyTarget: 90, weight: 4, sticker: "✨", color: "#6D8B74" },
  { code: "ACT022", name: "تمرین شکرگزاری", category: "ذهن‌آگاهی" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "BOOLEAN" as DataType, dailyTarget: 1, weeklyTarget: 7, monthlyTarget: 30, weight: 4, sticker: "🌸", color: "#9A8C98" },
  { code: "ACT023", name: "زمان شخصی", category: "مراقبت از خود" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "DURATION" as DataType, dailyTarget: 20, weeklyTarget: 140, monthlyTarget: 600, weight: 4, sticker: "🛁", color: "#C08497" },
  { code: "ACT024", name: "انجام یک فعالیت لذت‌بخش", category: "مراقبت از خود" as ActivityCategory, frequency: "WEEKLY" as Frequency, dataType: "BOOLEAN" as DataType, dailyTarget: 1, weeklyTarget: 3, monthlyTarget: 12, weight: 3, sticker: "🎨", color: "#B565A7" },
  { code: "ACT025", name: "اولویت‌بندی کارهای روز", category: "بهره‌وری" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "BOOLEAN" as DataType, dailyTarget: 1, weeklyTarget: 7, monthlyTarget: 30, weight: 4, sticker: "✅", color: "#E09F3E" },
  { code: "ACT026", name: "انجام مهم‌ترین کار روز", category: "بهره‌وری" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "BOOLEAN" as DataType, dailyTarget: 1, weeklyTarget: 7, monthlyTarget: 30, weight: 5, sticker: "🔥", color: "#D9A441" },
  { code: "ACT027", name: "مرور هفتگی", category: "بهره‌وری" as ActivityCategory, frequency: "WEEKLY" as Frequency, dataType: "DURATION" as DataType, dailyTarget: 0, weeklyTarget: 30, monthlyTarget: 120, weight: 4, sticker: "📅", color: "#4F7CAC" },
  { code: "ACT028", name: "خواندن کتاب", category: "یادگیری" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "DURATION" as DataType, dailyTarget: 20, weeklyTarget: 140, monthlyTarget: 600, weight: 4, sticker: "📖", color: "#B07D3C" },
  { code: "ACT029", name: "تکمیل یک فصل کتاب", category: "یادگیری" as ActivityCategory, frequency: "WEEKLY" as Frequency, dataType: "NUMERIC" as DataType, dailyTarget: 0, weeklyTarget: 1, monthlyTarget: 4, weight: 3, sticker: "📗", color: "#A86F52" },
  { code: "ACT030", name: "خواندن یک کتاب کامل", category: "یادگیری" as ActivityCategory, frequency: "MONTHLY" as Frequency, dataType: "NUMERIC" as DataType, dailyTarget: 0, weeklyTarget: 0, monthlyTarget: 1, weight: 5, sticker: "📘", color: "#D99A2B" },
  { code: "ACT031", name: "یک روز کامل بدون شبکه اجتماعی", category: "سبک زندگی" as ActivityCategory, frequency: "MONTHLY" as Frequency, dataType: "BOOLEAN" as DataType, dailyTarget: 0, weeklyTarget: 0, monthlyTarget: 1, weight: 4, sticker: "📵", color: "#5B8E7D" },
  { code: "ACT032", name: "مرور ماه و ارزیابی شخصی", category: "رشد فردی" as ActivityCategory, frequency: "MONTHLY" as Frequency, dataType: "BOOLEAN" as DataType, dailyTarget: 0, weeklyTarget: 0, monthlyTarget: 1, weight: 5, sticker: "🪞", color: "#7C6CE7" },
  { code: "ACT033", name: "تعیین اهداف ماه آینده", category: "رشد فردی" as ActivityCategory, frequency: "MONTHLY" as Frequency, dataType: "BOOLEAN" as DataType, dailyTarget: 0, weeklyTarget: 0, monthlyTarget: 1, weight: 5, sticker: "🧭", color: "#4F7CAC" },
  { code: "ACT034", name: "غذای سالم", category: "سلامت جسم" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "BOOLEAN" as DataType, dailyTarget: 1, weeklyTarget: 7, monthlyTarget: 30, weight: 4, sticker: "🥗", color: "#6A994E" },
  { code: "ACT035", name: "کاهش مصرف قند", category: "سلامت جسم" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "BOOLEAN" as DataType, dailyTarget: 1, weeklyTarget: 7, monthlyTarget: 30, weight: 4, sticker: "🍬", color: "#BC6C25" },
  { code: "ACT036", name: "کشش بدن", category: "سلامت جسم" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "DURATION" as DataType, dailyTarget: 10, weeklyTarget: 50, monthlyTarget: 200, weight: 3, sticker: "🤸", color: "#76A5AF" },
  { code: "ACT037", name: "نوشتن افکار و احساسات", category: "سلامت روان" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "DURATION" as DataType, dailyTarget: 10, weeklyTarget: 50, monthlyTarget: 200, weight: 4, sticker: "💭", color: "#8064A2" },
  { code: "ACT038", name: "فاصله گرفتن آگاهانه هنگام تنش", category: "سلامت روان" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "BOOLEAN" as DataType, dailyTarget: 1, weeklyTarget: 7, monthlyTarget: 30, weight: 5, sticker: "🌿", color: "#739E9B" },
  { code: "ACT039", name: "گفت‌وگوی بدون موبایل", category: "روابط" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "DURATION" as DataType, dailyTarget: 15, weeklyTarget: 105, monthlyTarget: 450, weight: 4, sticker: "💬", color: "#C45B8A" },
  { code: "ACT040", name: "یک کار در هر لحظه", category: "تمرکز و ذهن" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "BOOLEAN" as DataType, dailyTarget: 1, weeklyTarget: 7, monthlyTarget: 30, weight: 4, sticker: "🎧", color: "#547AA5" },
  { code: "ACT041", name: "خاموش‌کردن صفحه‌نمایش قبل از خواب", category: "خواب و استراحت" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "DURATION" as DataType, dailyTarget: 30, weeklyTarget: 210, monthlyTarget: 900, weight: 4, sticker: "🖥️", color: "#5964B4" },
  { code: "ACT042", name: "مراقبت شخصی", category: "مراقبت از خود" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "BOOLEAN" as DataType, dailyTarget: 1, weeklyTarget: 7, monthlyTarget: 30, weight: 3, sticker: "🧴", color: "#C08497" },
  { code: "ACT043", name: "جمع‌بندی پایان روز", category: "بهره‌وری" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "DURATION" as DataType, dailyTarget: 5, weeklyTarget: 35, monthlyTarget: 150, weight: 3, sticker: "🌇", color: "#7A9E7E" },
  { code: "ACT044", name: "بررسی یک رفتار و یادگیری از آن", category: "رشد فردی" as ActivityCategory, frequency: "DAILY" as Frequency, dataType: "DURATION" as DataType, dailyTarget: 10, weeklyTarget: 70, monthlyTarget: 300, weight: 4, sticker: "🔍", color: "#6B7AA1" },
  { code: "ACT045", name: "انجام یک تجربه جدید", category: "رشد فردی" as ActivityCategory, frequency: "MONTHLY" as Frequency, dataType: "BOOLEAN" as DataType, dailyTarget: 0, weeklyTarget: 0, monthlyTarget: 1, weight: 3, sticker: "🌈", color: "#D17A22" },
];

export function buildSeedActivities(userId: string, now = new Date().toISOString()): ActivityDefinition[] {
  return ROWS.map((row) => ({
    id: `${userId}-${row.code.toLowerCase()}`,
    userId,
    code: row.code,
    name: row.name,
    category: row.category,
    frequency: row.frequency,
    dataType: row.dataType,
    dailyTarget: row.dailyTarget,
    weeklyTarget: row.weeklyTarget,
    monthlyTarget: row.monthlyTarget,
    weight: row.weight,
    sticker: row.sticker,
    color: row.color,
    status: "ACTIVE",
    isSeed: true,
    createdAt: now,
    updatedAt: now,
  }));
}
export const SEED_ACTIVITY_COUNT = ROWS.length;
