// This file is automatically generated. Do not edit it directly.
// لایه اتصال به Supabase — با متغیرهای محیطی پیکربندی می‌شود.
//
// اگر VITE_SUPABASE_URL و VITE_SUPABASE_ANON_KEY تنظیم نشده باشند،
// اپلیکیشن به صورت خودکار در «حالت دمو» اجرا می‌شود (داده‌های seed
// در localStorage) و هیچ خطایی رخ نمی‌دهد. برای فعال‌سازی بک‌اند واقعی:
//   1) یک پروژه Supabase بسازید
//   2) فایل supabase/migrations را اجرا کنید
//   3) فایل .env.local بسازید و دو متغیر زیر را مقدار دهید

import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as
  | string
  | undefined;

export const isSupabaseConfigured = Boolean(
  SUPABASE_URL &&
    SUPABASE_PUBLISHABLE_KEY &&
    SUPABASE_URL.startsWith("http")
);

export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : (undefined as unknown as ReturnType<typeof createClient<Database>>);
